name: Docker Image CI

on:
  push:
   tags:
        - 'v*.*.*'

env:
  docker_repo: astin75/fibonacci        

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }} 

      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with :
      #     context : .
      #     push : true
      #     tags: ${{ env.docker_repo }}:${{ steps.vars.outputs.tag }}
      

      - uses: actions/checkout@v3
        name: Checkout private tools
        with:
          repository: astin75/git_ops
          token: ${{ secrets.PERSONAL_ACCESS_TOKENS }} 
      - run: |
          date > generated.txt
          git add .
          git commit -m "generated"
          git push

      
        

