name: Docker Image CI

on:
  push:
   tags:
        - 'v*.*.*'

env:
  RELEASE_VERSION: ${{ github.ref }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:


      - name: Login to Docker Hub
      - uses: docker/login-action@v2
      - with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    
    
      - name: Build the Docker image
      - uses: actions/checkout@v3
        run: docker build . --file Dockerfile --tag astin75/fibonacci:$RELEASE_VERSION
